### ISSUE TITLE
Centos8 Packer Build Need Urgent Attention

### ISSUE THREAD

**Issue by fenar** [canonical/packer-maas#10]
(i) Packer JSON needs to be updated to comply with new packer handler, although packer fix can correct syntax.
(ii) Centos8 image seems missing grub2-efi-x64-modules package that causes grub2 to not load properly at deployment time.
(iii) It looks qemu-nbd needs "sudo" to run properly also , "sudo partprobe" looks missing otherwise export from VM to mounted volume cannot happen.
--> all these covered & fixed in my fork https://github.com/fenar/packer-maas

However, there is still a deployment time issue with the generated Centos8 image that causes deployment to halt and I sincerely believe that is related with brctl util which is discontinued in Centos8 however I could not pull logs yet to provide it as I cannot ssh to node.

**Comment by ltrager** [comment]
Thanks for reporting this.

(i) master has been updated to comply with the new syntax
(ii) This is actually a bug in Curtin. See [LP:1895067](https://bugs.launchpad.net/curtin/+bug/1895067).
(iii) packer-maas is meant to be executed as root. This allows administrators to have to only allow giving packer sudo access instead of each individual command. Templates will now verify this.
