### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by dsever** [canonical/packer-maas#26]
Hi,

We have one software that comes as Arch Linux Live ISO image, and we would like to provisioned it by  MaaS. By any chance, do do have in plan to share Arch linux json definition as well?

Thanks

**Comment by ltrager** [comment]
We do not currently have any plans to support Arch Linux. MAAS uses [LP:Curtin](https://launchpad.net/curtin/) to perform the installation which does look it has Arch support. If you create a tgz of the installation it may work.

**Comment by dsever** [comment]
If I understand you right, simple tar.gz of ISO content might work?

**Comment by ltrager** [comment]
No you'd need to create a tar.gz of the contents of an installed system. MAAS/Curtin don't run the OS installer it formats the disks and extracts the tar over the formatted disks or writes a disk image directly to disk. It then configures networking and cloud-init.

**Comment by dsever** [comment]
So as I assumed,  so it will not fly for us, because we would like  MaaS to deploy live ISO, without writing anything on the local disks.

**Comment by sempervictus** [comment]
When you say "deploy live ISO," do you mean boot from PXE into an Arch environment into the commission state (or something like that as a runtime)? Like replacing the microkernel image in Razor?
The TGZ approach is viable though, Arch is silly-simple and can even run `netplan` (although seems like a needless added layer of complexity). Snaps work rather well too. Cloud images for Arch are pretty easy to make, but how do you deal with the variance in deployment between EFI and MBR systems? Our in-house images are GPT with an MBR block embedded at the start of the volume containing both EFI and boot partitions readable by grub, with a(n encrypted) data partition (well, ZFS rpool).

**Comment by ltrager** [comment]
@dsever MAAS supports ephemeral deployments but only for Ubuntu. The easiest way to do that is by deleting all disks from the machine and then deploying whatever Ubuntu version you want to use. MAAS doesn't support ephemeral deployments for other operating systems because we need an initrd with all drivers available and specialized scripts to download the rootfs.

@sempervictus When Curtin formats the disks it determines whether GPT or MBR should be used based on whether the system is UEFI. The tar.gz itself only contains the files of the operating system, not a disk image.
