### ISSUE TITLE
setup-nbd loops for nothing for partition creation!

### ISSUE THREAD

**Issue by fenar** [canonical/packer-maas#29]
please add "sudo partprobe $nbd" before while looping to check if "${nbd}p1" partitions created, lol :-).

**Comment by ltrager** [comment]
partprobe is a non-blocking call to the kernel to rescan a block device for partitions. It should automatically be run when `qemu-nbd` is called. The loop is there so packer-maas waits for the partitions to be created.

packer-maas originally used partprobe with standard loopback devices. This method caused many build failures which is why I replaced it with `qemu-nbd`
