### ISSUE TITLE
Provision Oracle Linux OS on MAAS?

### ISSUE THREAD

**Issue by richardsmnjtk** [canonical/packer-maas#89]
I want to provision Oracle linux OS, but MAAS doesn't have support for that OS yet.
Is there any alternative that I can use to provision Oracle Linux in MAAS?

**Comment by troyanov** [comment]
Hi @richardsmnjtk 
Adding Oracle Linux is on our roadmap, but we don't have any estimations when it will be implemented. Please check with us in May - we should know by then if support for Oracle Linux is in our short term plans. 

Oracle Linux is similar to RHEL and CentOS, so you could try to start with packer-maas templates for these distributions and modify them for your needs. It may be necessary to update [curtin](https://launchpad.net/curtin) to recognise Oracle Linux too. If you'd like to give it a shot, we love community contributions!

**Comment by richardsmnjtk** [comment]
Hi @troyanov 
Do you have any guide to update the curtin? 
Because I just have this instruction [**](https://askubuntu.com/questions/882911/how-do-i-use-maas-to-create-a-debian-image/973247#973247) and didn't work.

**Comment by troyanov** [comment]
I believe information about Oracle Linux should be added to [curtin](https://github.com/canonical/curtin/blob/master/curtin/distro.py) itself

Then update `curtin` that is used by MAAS:
For `snap` builds it takes version from [MAAS PPA](https://launchpad.net/~maas/+archive/ubuntu/3.2/+packages), but in case of a `deb` installation, it can be forced to use a different version installed on the system.

Also this [post](https://discourse.maas.io/t/support-for-rockylinux/4760) on Discourse might be helpful, since steps to add a new distro are somehow similar:
1. Make sure curtin knows how to install distro
2. Build a custom distro image with `cloud-init` using `Packer`
